### ISSUE TITLE
Upload to Arduino Micro from Raspberry Pi failed with 'programmer is not responding'

### ISSUE THREAD

**Issue by benjamind** [sudar/Arduino-Makefile#127]
When I try and upload to an Arduino Micro from a Raspberry Pi I get the following error:

``` bash
Connecting to programmer: .avrdude: butterfly_recv(): programmer is not responding
```

I have poked around as much as I can and I'm not sure whats going on here. Other programmers such as [ino](http://inotool.org/) work fine, but I'd rather using the Arduino-Makefile project if I can since it seems easier to update and manage.

Any ideas?

**Comment by fjrg76mx** [comment]
In exaactly one year before that last post from "sudar" I'm facing the same problem: I need to reset the board by hand while the command sudo make upload is starting. I made it work in that way, and the code was uploaded. However the led is not blinking.

I'm using arduino-core and Arduino.mk from the official repositories from Linux Mint 17.1. for the Leonardo's board.

Any ideas?

Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

avrdude: AVR device initialized and ready to accept instructions
avrdude: Device signature = 0x1e9587
avrdude: reading input file "build-leonardo/CortinasArd.hex"
avrdude: writing flash (1060 bytes):
avrdude: 1060 bytes of flash written

avrdude: safemode: Fuses OK (H:CB, E:D8, L:FF)

avrdude done.  Thank you.

**Comment by sej7278** [comment]
@fjrg76mx need much more info than that - like the full arduino-mk output and your Makefile.

also have you tried using arduino-mk from git, what version is in mint 17.1 - if its based on ubuntu 14.04 then its 1.3.1 which is over a year old.

if you want a (debian) package then try [this](http://www.the-jedi.co.uk/downloads/arduino/arduino-mk_1.3.4-2_all.deb), build of 1.3.4, its only a few weeks old
