### ISSUE TITLE
Passing in Arguments from Command line through Makefile to Arduino 

### ISSUE THREAD

**Issue by ghost** [sudar/Arduino-Makefile#227]
I am interested to pass in 2 variables, USERNAME and PASSWORD via command line in the form of: 

```
make USERNAME=123 PASSWORD=123
make upload
```

I have the following defined: 

```
BOARD_TAG = mega2560
CPPFLAGS =  -DUSERNAME=$(USERNAME) -DPASSWORD=$(PASSWORD)
include $(ARDMK_DIR)/Arduino.mk
```

```
String auth_raw = USERNAME + ":" + PASSWORD;
```

I am getting this error, 

```
../base/Base.h:185:43: error: expected primary-expression before ‘;’ token
```

Any ideas why?

**Comment by xxEoD2242** [comment]
Although this is closed, the issue that you are experiencing deals with the fact that whatever type is passed into the IDE as a global variable is most likely not the String class in Arduino. I've dealt with several of these issues. Try to explicitly cast the values as a String type using the following:
```
String username = String(USERNAME);
```

This will convert everything to a string and then you can use the '+' feature of the String library.

A more C++ way to handle this would be cast the variable as a char array and then typecast to a string later in the code.

Hope this helps and please, anyone, tell me if I am off base with this one.
