### ISSUE TITLE
Flymake instructions say to use $(CXX_NAME) instead of the correct $(CXX)

### ISSUE THREAD

**Issue by admiralbumblebee** [sudar/Arduino-Makefile#309]
Flymake instructions say to use $(CXX_NAME) refers to simply avr-g++.
 
It should be $(CXX) since that refers to the full path + the cxx name.

**Comment by sej7278** [comment]
its a bit pedantic, with either you could define it to be the full path or just the avr-g++ binary, although the "standard" would be to call it $(CXX) as per http://www.emacswiki.org/emacs/FlyMake

**Comment by admiralbumblebee** [comment]
Thank you, and happy new year to you too!
