### ISSUE TITLE
runtests.sh and bootstrap.sh Fail to run

### ISSUE THREAD

**Issue by abferm** [sudar/Arduino-Makefile#367]
Hello, I cloned the repository into a path that includes spaces. Both scripts make multiple references to the working directory, and in several cases do not provide all necessary '"'s. I was able to solve this by renaming my directory without the ' ' character, but this should not be required, as you have no control over where someone clones the repository to.

**Comment by sej7278** [comment]
you should not be running either of those scripts, they are purely for the travis-ci tests

using spaces in paths is just asking for trouble when it comes to any sort of programming
