### ISSUE TITLE
Looking for hex in wrong directory

### ISSUE THREAD

**Issue by abferm** [sudar/Arduino-Makefile#368]
Sorry to post so many things around the same time, but something is looking for files out of the root directory rather than the current one after the compile finishes when I run `make`.

----------------
Device: atmega328p

Program:    5152 bytes (15.7% Full)
(.text + .data + .bootloader)

Data:        257 bytes (12.5% Full)
(.data + .bss + .noinit)

/usr/bin/avr-size: 'a.out': No such file
/bin/sh: 1: /bin/uno/elseif/elseif.hex: not found
/bin/sh: 1: [: Illegal number: pwd

**Comment by sej7278** [comment]
we don't call pwd in any of the makefiles, so you must be incorrectly running the test suite
