### ISSUE TITLE
How can I exit from the monitor target?

### ISSUE THREAD

**Issue by daitangio** [sudar/Arduino-Makefile#384]
Hi, under macosx when I issue "make monitor" I did not know what is the best way to exit from it.
If I detach screen, it will continue to run.
Also if I quit screen I need to reset my terminal.
What is the best way of doing it?

**Comment by sej7278** [comment]
ctrl-a, then k, then "yes"

**Comment by sej7278** [comment]
@daitangio does that work for you? 

i don't understand about quitting screen requiring you to reset your terminal. how are you quitting?

**Comment by ladislas** [comment]
@sej7278 if you unplug the usb cable, you exit from screen but can't using again if you don't close and reopen the terminal

**Comment by sej7278** [comment]
@ladislas well yes, because you've not disconnected from screen, you've just yanked the cable and killed the serial connection, its still running within screen, but that's to be expected.

**Comment by daitangio** [comment]
Hi thank you!! If you detach screen you may have issue

**Comment by sej7278** [comment]
oddly enough i just accidentally pulled the usb cable in the middle of a "make monitor" and when i reran "make monitor" it reconnected fine, but that's linux

**Comment by ladislas** [comment]
![](http://i.imgur.com/ZMmgsRl.jpg)

**Comment by sej7278** [comment]
;)

**Comment by santids** [comment]
ctrl-a, then k, then "yes", works, though I think is not very elegant. Should be in the documentation maybe

**Comment by sej7278** [comment]
it defaults to gnu screen which is the standard terminal emulator for most unixen, but as it can be overridden and replaced with minicom or whatever its difficult to document. PR's are always welcome
