### ISSUE TITLE
Support for Arduino/Genuino 101

### ISSUE THREAD

**Issue by maxbrueckl** [sudar/Arduino-Makefile#410]
The latest Arduino board comes with an Intel Curie and therefore with a whole other toolchain (ARC-elf32). 

For reference: 
https://www.arduino.cc/en/Main/ArduinoBoard101
http://www.intel.com/content/www/us/en/wearables/intel-curie-fact-sheet.html

Any chance to support this by the makefile?

**Comment by sudar** [comment]
Right now this makefile only supports avr toolchain. Adding support for other tool chains is in the todo list. 

So to answer your question, we don't have support for it now, but would like to add it.

**Comment by idone-wangqiang** [comment]
Hi,does this Makefile support now?

**Comment by markdegrootnl** [comment]
Any update on this?
