### ISSUE TITLE
Fuse set problem

### ISSUE THREAD

**Issue by thalesmaoa** [sudar/Arduino-Makefile#417]
Hi, I have all my make configured, but when I try to set fuses, they don't work.

> ISP_LOCK_FUSE_PRE  = 0xfc
> ISP_LOCK_FUSE_POST = 0xfc
> ISP_HIGH_FUSE      = 0xd9
> ISP_LOW_FUSE       = 0xff
> ISP_EXT_FUSE       = 0xfc

But I can only get them working with:

> AVRDUDE_OPTS      = -U hfuse:w:0xD9:m -U lfuse:w:0xFF:m -U efuse:w:0xFC:m -v -v

Besides, AVRDUDE_OPTS run before the erase process, but the fuses are supposed to write after.

Any idea?

**Comment by sudar** [comment]
Can you post your entire makefile and the complete output?

**Comment by sej7278** [comment]
yes can't really tell without the Makefile and output.

i've never tried using lock bits, but your AVRDUDE_OPTS has skipped them too, have you tried removing them from your Makefile to see if the h/l/e fuses get set then?

also avrdude ignores unset bits, so 0xFF should be 0x07, i've come across that problem myself.

ref. http://www.avrfreaks.net/comment/673717#comment-673717

**Comment by thalesmaoa** [comment]
Thanks

Makefile
http://pastebin.com/CShtKUKY

With that file I have the following output:

http://pastebin.com/2J4LXEXf
No fuses written.
If I change:
`AVRDUDE_OPTS 	    = -U hfuse:w:0xD9:m -U lfuse:w:0xFF:m -U efuse:w:0xFC:m -v -v`

I get the following:

http://pastebin.com/yrFwGJxC

Fuses are written but out of order

**Comment by sej7278** [comment]
ah i see the problem - ```make ispload``` doesn't set the fuses, you do that with ```make set_fuses```.

```make burn_bootloader``` uploads the sketch, bootloader and sets the fuses, but we separated out the fuse and ispload recipes.

in your second test case, this is a known [avrdude bug](http://savannah.nongnu.org/bugs/?40794), you can see it reads the 3 fuses in the correct order, but then the last line is out of order - just ignore the last line or upgrade to avrdude 6.1 or later.

```
avrdude: safemode: lfuse reads as FF 
avrdude: safemode: hfuse reads as D9  
avrdude: safemode: efuse reads as FC  
avrdude: safemode: Fuses OK (H:FC, E:D9, L:FF)    <-- only this line is wrong
```

**Comment by thalesmaoa** [comment]
Very good to know, thank you.

About the order, I was referring that lock bits are reset during chip
erase. So I must set them after burn my code.

Using in avr_options they all set before, and them I lost my lock fuse.

Now I will try make set_fuse after ispload.

Thank you
Em 02/03/2016 10:24 PM, "Simon John" <notifications@github.com> escreveu:

**Comment by thalesmaoa** [comment]
Perfect! Works very well

I was wondering, is there a way to create custom targets?

`make project1`
`make project2`

In general, I work with the same program files, but in the lines codes, I just need to change a few variables:

Project 01
`int x = 1`

Project 02
`int x = 2`

If I create a target in make file, I can create multiple definition files:

`var_proj1.cpp`
`var_proj2.cpp`

And them just copy and rename it:
`make project1`
Inside Makefile:
`mv var_proj1.cpp var_proj.cpp`

Where var_proj.cpp is the real include in my main.cpp.
`#include "var_proj.cpp"`

**Comment by sej7278** [comment]
i think you should probably look at preprocessor defines (-D flag) so you can just modify what the code does based in a variable, rather than using separate files and moving them:

https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html#Preprocessor-Options

**Comment by thalesmaoa** [comment]
When I use make set_fuses my processor is erased.

**Comment by thalesmaoa** [comment]
I found a problem:

`ifneq ($(strip $(AVRDUDE_ISP_FUSES_PRE)),)`

Always runs true and my processor is always erased

**Comment by sej7278** [comment]
see: https://github.com/sudar/Arduino-Makefile/blob/master/Arduino.mk#L1308

if you set ```AVRDUDE_ARD_OPTS``` and override the defaults, make sure to include the -D flag

**Comment by thalesmaoa** [comment]
-D flag is not a solution.

Please, take a look at:
https://github.com/sudar/Arduino-Makefile/blob/master/Arduino.mk#L1471

ISP_LOCK_FUSE_PRE means that the lock fuse is perform before the burning, which means that -e flag is ok.
ISP_LOCK_FUSE_POST means that the lock fuse is perform after the burning.

In my case, I just only set the post flag, but it happens that both are run.
First it run the pre and after the post.
It is doing write, first -e and after not.

The problem is that:

`ifneq ($(strip $(AVRDUDE_ISP_FUSES_PRE)),)`

is always true when I try make set_fuses

**Comment by sej7278** [comment]
you can only use one lock command - so either PRE or POST not both. it doesn't really make sense to use the -e flag with POST and both of your PRE and POST values are the same, so just use PRE not POST i guess

**Comment by thalesmaoa** [comment]
Indeed, I do not use PRE, only POST, but as I mentioned, I always runs PRE. The conditional is always true no matter what.
It seems a bug.

**Comment by sej7278** [comment]
could you try changing:

```
ifneq ($(strip $(AVRDUDE_ISP_FUSES_PRE)),)
```

to:

```
ifndef AVRDUDE_ISP_FUSES_PRE
```

**Comment by sej7278** [comment]
yup, AVRDUDE_ISP_FUSES_PRE is always going to be defined and non-empty if you set any of the fuse variables:

https://github.com/sudar/Arduino-Makefile/blob/master/Arduino.mk#L1340

unless you can figure out a fix, the workaround is to use PRE not POST

**Comment by thalesmaoa** [comment]
`ifneq ($(strip $(AVRDUDE_ISP_FUSES_PRE)),)`

replace by

`ifneq ($(ISP_LOCK_FUSE_PRE),)`

If not set, do nothing.

**Comment by sej7278** [comment]
don't confuse lock fuse with isp fuse, almost nobody uses lock fuses and that change would force everyone to use the lock fuse!

**Comment by thalesmaoa** [comment]
I will generate a pull request soon.

**Comment by thalesmaoa** [comment]
Sorry, didn't have time to try, but I would propose something like:

set_fuses:
ifdef ISP_LOCK_FUSE_PRE
	ifdef ISP_LOCK_FUSE_POST
		$(error Only set one lock fuse, pre or post)
	else
		AVRDUDE_ISP_OPTS += -e
	endif
endif

ifneq ($(strip $(AVRDUDE_ISP_FUSES_PRE)),)
		$(AVRDUDE) $(AVRDUDE_COM_OPTS) $(AVRDUDE_ISP_OPTS) $(AVRDUDE_ISP_FUSES_PRE)
endif
ifneq ($(strip $(AVRDUDE_ISP_FUSES_POST)),)
		$(AVRDUDE) $(AVRDUDE_COM_OPTS) $(AVRDUDE_ISP_OPTS) $(AVRDUDE_ISP_FUSES_POST)
endif
