### ISSUE TITLE
The project's generic name makes it impossible to search the Internet for specific usage examples

### ISSUE THREAD

**Issue by tullo-x86** [sudar/Arduino-Makefile#425]
Try Googling for "Arduino-Makefile teensy 3" and see what results you get. It's almost as bad as searching for information on that dreadfully-named "anarduino" board.

Suggested solution: Ditch the working title and pick a name. How about "Slartibartfast"? There doesn't seem to be a library or makefile script named that ...yet. Honestly, I don't really care what it is, so long as it's unique enough to have a strong signal-to-noise ratio in search results.

**Comment by sudar** [comment]
I agree with you that the name "Arduino Makefile" is very generic and doesn't bring us any real SEO value.

But renaming the project now, might break lot of things including the different package that are created for this project, this github repo name etc.

So I don't think it would be possible for us to rename now.
