### ISSUE TITLE
Binary file is greater than the Uno's memory (Windows)

### ISSUE THREAD

**Issue by markglavind** [sudar/Arduino-Makefile#427]
I'm having trouble with uploading the sketch to the Arduino, where i am getting the following errors

> AVR Memory Usage
> ----------------
> Device: atmega328p
> 
> Program:    1088 bytes (3.3% Full)
> (.text + .data + .bootloader)

> Data:          9 bytes (0.4% Full)
> (.data + .bss + .noinit)

> /c/cygwin64/bin/awk: /c/cygwin64/bin/awk: cannot execute binary file
> /usr/bin/sh: [: -le: unary operator expected
> \nThe size of the compiled binary file is greater than the uno's flash memory. See http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
> make: *** [verify_size] Error 1

However, the file should be nowhere near the size of maxing out the Arduino? Except for a libcore.a file with a size of 89KB.

This is my Makefile:
>BOARD_TAG    = uno
>MONITOR_PORT = /dev/cu.usb*
>AVRDUDE      = C:/WinAVR-20100110/bin
>#OBJDIR       = C:/Users/Mark/Desktop/Arduino-MakeFile/Arduino-Makefile-master/Blink
>ARDUINO_DIR = C:/Users/Mark/Desktop/Arduino-MakeFile/Arduino-Makefile-master/ArduinoFiles
>AVR_TOOLS_DIR = C:/Users/Mark/Desktop/Arduino-MakeFile/Arduino-Makefile-master/AvrFiles
>#BOARDS_TXT = C:/Users/Mark/Desktop/Arduino-MakeFile/Arduino-Makefile-master/ArduinoFiles/hardware/arduino/boards.txt

>include /Users/Mark/Desktop/Arduino-MakeFile/Arduino-Makefile-master/Arduino.mk

**Comment by sej7278** [comment]
i assume line [1261](https://github.com/sudar/Arduino-Makefile/blob/master/Arduino.mk#L1261) is the problem, perhaps with the backticks? maybe cygwin's version of awk is out-of-date?

**Comment by markglavind** [comment]
Sorry, but im not sure what you mean with the backticks? My cygwin install is fresh, so i would guess i have the newest version
