### ISSUE TITLE
Using Arduino-makefile to build stk500v2 bootloader

### ISSUE THREAD

**Issue by erathos** [sudar/Arduino-Makefile#432]
For testing, I compiled in terminal without displayed error  the stk500boot.c bootloader together with avr_cpunames.h, command.h and boards.txt  files using this makefile in Arduino IDE 1.6.0 (or  IDE 1.0.6)(MacOS10.6.8), and next I compared the .hex file to the original one included in the IDE: I got strong mismatches. After disassembling the .elf file using the "avr-objdump -d -S -j .text" instruction in terminal, I got  on the beginning:

00000000 <__vectors>:
       0:	0c 94 51 03 	jmp	0x6a2	; 0x6a2 <__ctors_end>
       4:	0c 94 7a 03 	jmp	0x6f4	; 0x6f4 <__bad_interrupt>
       8:	0c 94 7a 03 	jmp	0x6f4	; 0x6f4 <__bad_interrupt>
…………….this line repeated 56 times until address:
    e0:	0c 94 7a 03 	jmp	0x6f4	; 0x6f4 <__bad_interrupt>
    e4:	3f 0a       	sbc	r3, r31
………..etc
followed by instructions without apparent errors (I am not an expert).
I have not already tried to upload this hex file to my mega2560 with avrISP mkII, waiting for your help:
Please, is this normal or what have I missed in the makefile ?
Does someone have already used this makefile to build a stk500v2 bootloader successfully ?
Is it normal that distinct makefile methods  led to strongly mismatched hex files ?
Thanks for any reply

**Comment by sej7278** [comment]
this makefile is the wrong thing for doing that, you should be using the makefile that comes with the bootloader, arduino-mk is for compiling sketches

https://github.com/arduino/Arduino-stk500v2-bootloader/blob/master/Makefile
