### ISSUE TITLE
Add support for Arduino 1.5

### ISSUE THREAD

**Issue by sudar** [sudar/Arduino-Makefile#45]
Arduino 1.5 has changed the directory structure. 

Add an option to specify (or auto detect) Arduino version and then based on that change the directory paths.

Changes should be compatible with 1.0.x version of Arduino as well.

**Comment by daitangio** [comment]
I works on my IDE 1.5.8. It also autodetects all the environment variables.
A very very nice work!

**Comment by mulderp** [comment]
it works with the Arduino IDE 1.6 too

**Comment by sej7278** [comment]
@mulderp which are you talking about, this Arduino-Makefile or xxxajk's Arduino_Makefile_master ?

this makefile supports 1.6.1 for a lot of the AVR chips and teensy, not ARM, although the IDE 1.6.2 that just got released has broken a lot of it (well the IDE itself is broken on linux at least).

**Comment by mulderp** [comment]
I tried this project with the Blink example and Arduino 1.6.0

In fact, I think this project is great. I wrote some thoughts about command line usage for Arduino here:

http://thinkingonthinking.com/an-arduino-sketch-from-scratch/

**Comment by sudar** [comment]
As of today, master supports Arduino 1.6.3, hence closing this.

Support for SAM and other non-avr boards is not available yet. It will be tracked in #343

**Comment by xxxajk** [comment]
Oh and happy Easter, I'm just not one for traditional holidays.

On Sun, Apr 5, 2015 at 11:40 PM, Sudar Muthu <notifications@github.com>
wrote:

> As of today, master supports Arduino 1.6.3, hence closing this.
>
> Support for SAM and other non-avr boards is not available yet. It will be
> tracked in #343 <https://github.com/sudar/Arduino-Makefile/issues/343>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sudar/Arduino-Makefile/issues/45#issuecomment-89907253>
> .
>



-- 
Visit my github for awesome Arduino code @ https://github.com/xxxajk
