### ISSUE TITLE
AVR_TOOLS_DIR variable is ignored

### ISSUE THREAD

**Issue by imranmunshi** [sudar/Arduino-Makefile#462]
I am on Arch Linux and using arduino-mk from AUR.

I have installed avr-gcc, avr-binutils and avr-libc (ver. 6.20) and to use that I set AVR_TOOLS_DIR to /usr but it still shows /usr/share/arduino/..... (the default calculated value) in the make output and the same is used. I want to use the latest avr-gcc toolchain

**Comment by ladislas** [comment]
can we see the makefile? maybe you added AVR_TOOLS_DIR after the include at the end.

**Comment by imranmunshi** [comment]
Here it is:

ALTERNATE_CORE = edtracker
BOARD_TAG = edtracker9150
VARIANT = edtracker2-9150
ARDUINO_PLATFORM_LIB_PATH = ${HOME}/Arduino/hardware/edtracker/avr/libraries
ARDUINO_LIBS = Wire EEPROM I2Cdev InvensenseMotionDriver Adafruit-PWM-Servo-Driver-Library
AVR_TOOLS_DIR = /usr
include /usr/share/arduino/Arduino.mk
ALTERNATE_CORE = edtracker
BOARD_TAG = edtracker9150
VARIANT = edtracker2-9150
ARDUINO_PLATFORM_LIB_PATH = ${HOME}/Arduino/hardware/edtracker/avr/libraries
ARDUINO_LIBS = Wire EEPROM I2Cdev InvensenseMotionDriver Adafruit-PWM-Servo-Driver-Library
AVR_TOOLS_DIR = /usr
include /usr/share/arduino/Arduino.mk

**Comment by ladislas** [comment]
remove the first  include /usr/share/arduino/Arduino.mk

**Comment by imranmunshi** [comment]
Already tried that. Here is what I get
 [USER]               AVR_TOOLS_DIR = /usr/share/arduino/hardware/tools/avr

**Comment by ladislas** [comment]
are you sure that what you posted is your **actual** Makefile? also why do you want to use avr-gcc 6.2?

try this:

```
ALTERNATE_CORE = edtracker
BOARD_TAG = edtracker9150
VARIANT = edtracker2-9150
ARDUINO_PLATFORM_LIB_PATH = ${HOME}/Arduino/hardware/edtracker/avr/libraries
ARDUINO_LIBS = Wire EEPROM I2Cdev InvensenseMotionDriver Adafruit-PWM-Servo-Driver-Library
AVR_TOOLS_DIR = /usr/local
include /usr/share/arduino/Arduino.mk
```

**Comment by imranmunshi** [comment]
Yes, that is exactly what I have.

I just want to try avr-gcc-6.2.0. I have build failure when using standard board tags like uno or micro (I will report it in an other issue)

**Comment by imranmunshi** [comment]
Does it have something to do with ARDMK_VERSION? Mine is 1.5

**Comment by ladislas** [comment]
try compiling a blink example with avr-gcc 6.2 and let me know if it works

**Comment by imranmunshi** [comment]
I tried with the latest pull from github and it works. It detects the AVR_TOOLS_DIR and uses avr-gcc-6.2.0 properly, although avr-gcc segfaults (lto1: internal compiler error: Seg fault)

**Comment by imranmunshi** [comment]
I guess this issue can be closed
