### ISSUE TITLE
ard-parse-boards does not locate/understand 3rd-party hardware directories.

### ISSUE THREAD

**Issue by jaysonlarose** [sudar/Arduino-Makefile#47]
As per http://arduino.cc/en/Guide/Environment#thirdpartyhardware , you are able to supplement the existing board libraries, core libraries, bootloaders, and programmer definitions without having to modify the originals by putting your additions in a new subdirectory in hardware/.

In other words, if your ARDUINO_DIR is `/usr/share/arduino` and you want to add a new board, the proper way to go about doing so is to create a new directory under `/usr/share/arduino/hardware` (I don't think the name matters, as long as it's not "arduino"), and put the relevant additions in there, following the same convention as the preexisting `/usr/share/arduino/hardware/arduino` directory.  Thus your add-on file structure would start to look like this:

```
/usr/share/arduino/hardware/myboard/boards.txt (containing JUST the new board definition(s)!)
/usr/share/arduino/hardware/myboard/bootloaders/MyBoardRev1/Makefile
/usr/share/arduino/hardware/myboard/bootloaders/MyBoardRev1/r1bootloader.c
/usr/share/arduino/hardware/myboard/bootloaders/MyBoardRev1/r1bootloader.hex
/usr/share/arduino/hardware/myboard/cores/MyBoardRev1/Arduino.h
```

(etc, etc)

ard-parse-boards doesn't seem to follow this hunt behavior, since it is passed the full pathname to just the arduino subdir's boards.txt file.  Instead, it should be provided with the base ARDUINO_DIR, so it can then check each subdirectory in ARDUINO_DIR/hardware/ for a boards.txt file, and use the information in each of these to compile the full boards list.

I also presume that every other component of Arduino-Makefile which may need to use data in ARDUINO_DIR/hardware will need to be modified to follow this behavior as well, making this a Pretty Big Modification to make.  But... it's what the Arduino IDE does.

**Comment by mgcrea** [comment]
Is the teensy 3.1 supposed to work now? Just tried with Arduino 1.6 with latest Teensyduino and it does not work.

**Comment by sej7278** [comment]
does teensy work with the 1.6 ide? last i heard paul-s only started working on it this month and its not finished.

teensy 3.1 works with 1.0.6 and most AVR devices seem to work with 1.6 except those with custom cores like attiny. realistically if you don't have an ARM board, don't use 1.6

**Comment by sej7278** [comment]
this shows the board and sub (cpu) for every board with a sub (which isn't every board):

```
$(shell for board in `cat $(BOARDS_TXT) | grep -E '^[a-zA-Z0-9_]+.name' | awk -F. {'print $1'} | sort -uf` ; do grep -E $board'.menu.cpu.[a-zA-Z0-9_]+=' $(BOARDS_TXT) | sed 's/.menu.cpu./:/;s/=/:/' ; done | column -s: -t)

atmegang   atmega168       ATmega168
atmegang   atmega8         ATmega8
bt         atmega328       ATmega328
bt         atmega168       ATmega168
diecimila  atmega328       ATmega328
diecimila  atmega168       ATmega168
lilypad    atmega328       ATmega328
lilypad    atmega168       ATmega168
mega       atmega2560      ATmega2560 (Mega 2560)
mega       atmega1280      ATmega1280
mini       atmega328       ATmega328
mini       atmega168       ATmega168
nano       atmega328       ATmega328
nano       atmega168       ATmega168
pro        16MHzatmega328  ATmega328 (5V, 16 MHz)
pro        8MHzatmega328   ATmega328 (3.3V, 8 MHz)
pro        16MHzatmega168  ATmega168 (5V, 16 MHz)
pro        8MHzatmega168   ATmega168 (3.3V, 8 MHz)

```

need to somehow merge it with "make show_boards"
