### ISSUE TITLE
Allowing to include files from additional folders (gcc -I)

### ISSUE THREAD

**Issue by roobre** [sudar/Arduino-Makefile#473]
It would be nice to have a variable to allow extra folders to be searched for headers, as sometimes you want to keep some headers on non-root directories (and `#include "lib/asd/asd.h"` is just way uglier than `#include <asd.h>`. 

This variable would be analogous to `LOCAL_C_SRCS` and `LOCAL_CPP_SRCS` (¿`LOCAL_HEADERS` maybe?)

**Comment by sej7278** [comment]
loks like a duplicate o f #438

**Comment by roobre** [comment]
I confirm it as a dupe, my fault for not seeing it. I'm closing this one, with your permission.
