### ISSUE TITLE
Unable to compile pulseIn code with Arduion 1.8.1

### ISSUE THREAD

**Issue by chrisspen** [sudar/Arduino-Makefile#478]
Using the makefile to compile any code using the standard `pulseIn()` function with Arduino 1.8.1 results in the error:

    usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,--gc-sections -Os -o build-uno/main.elf build-uno/main.o build-uno/libcore.a  -lc -lm
    build-uno/libcore.a(wiring_pulse.o): In function `pulseIn':
    wiring_pulse.c:(.text.pulseIn+0x38): undefined reference to `countPulseASM'
    collect2: error: ld returned 1 exit status
    /usr/share/arduino/Arduino.mk:1396: recipe for target 'build-uno/main.elf' failed
    make: *** [build-uno/main.elf] Error 1

**Comment by lezsakdomi** [comment]
For people found this from google, see https://github.com/sudar/Arduino-Makefile/issues/364
