### ISSUE TITLE
Add support for cu

### ISSUE THREAD

**Issue by mwm** [sudar/Arduino-Makefile#492]
Cu is the standard comms program for Unix. While it's not all that popular with the Linux generation, it ships as part of the base OS for Unix variants based on AT&T code (the BSD's, MacOS, Solaris, etc.). Seems like it'd be nice to have support for a command that's already there, especially on MacOS.

The diff is trivial, so I've included it here instead of making a real PR. If you really need the PR, let me know.

```
--- a/Arduino.mk
+++ b/Arduino.mk
@@ -1533,6 +1533,8 @@ ifeq ($(MONITOR_CMD), 'putty')
        endif
 else ifeq ($(MONITOR_CMD), picocom)
                $(MONITOR_CMD) -b $(MONITOR_BAUDRATE) $(MONITOR_PARAMS) $(call get_monitor_port)
+else ifeq ($(MONITOR_CMD), cu)
+               $(MONITOR_CMD) -l $(call get_monitor_port) -s $(MONITOR_BAUDRATE)
 else
                $(MONITOR_CMD) $(call get_monitor_port) $(MONITOR_BAUDRATE)
 endif
```

**Comment by sej7278** [comment]
Merged thanks @mwm
