### ISSUE TITLE
Add ability to connect to Arduino via serial port

### ISSUE THREAD

**Issue by chrisspen** [sudar/Arduino-Makefile#512]
This is a feature request. Inotools contains a useful feature to stream serial data from an Arduino by running `ino serial`. The docs don't mention similar feature, although the installation of pyserial is required. It would be very convenient to be able to do `make serial` and see any data being streamed by the Arduino over the serial connection.

**Comment by sej7278** [comment]
make monitor

**Comment by sej7278** [comment]
can we close this?
