### ISSUE TITLE
libmpfr.so.4 not found on archlinux

### ISSUE THREAD

**Issue by sandric** [sudar/Arduino-Makefile#549]
Trying to compile from within emacs I constantly getting error like this:

```
/usr/lib/gcc/avr/7.2.0/cc1plus:
error while loading shared libraries: libmpfr.so.4: cannot open shared object file:
No such file or directory
```
I tried to install mpfr package, and it populates `/usr/lib` with `libmpfr.so.6`, but not `libmpfr.so.4`. Any guess about that error?

**Comment by ladislas** [comment]
where did you get avr-gcc from?

**Comment by sandric** [comment]
@ladislas from `pacman -S avr-gcc`

**Comment by sandric** [comment]
Not matter anymore, resolved after `pacman -Suy`, so I'll close issue then.
