### ISSUE TITLE
Including sources from separate directories

### ISSUE THREAD

**Issue by birgersp** [sudar/Arduino-Makefile#551]
Hi,

I've gotten the impression that any source files used in my project has to in the same directory. Is this correct? If yes, I suggest that a feature is implemented to add multiple source directories.

**Comment by sej7278** [comment]
#249, #349 and kind of #438 cover this

**Comment by birgersp** [comment]
This one looks promising: https://github.com/sudar/Arduino-Makefile/pull/252

I can easily add local source files my self to the `LOCAL_CPP_SRCS` variable.

Why isn't the PR pulled?

**Comment by birgersp** [comment]
Ahh, I just realized I can add the names of my source files to `LOCAL_CPP_SRCS` to explicitly set which source files to build. Neat!
