### ISSUE TITLE
Calling <<-EOS.undent is disabled!

### ISSUE THREAD

**Issue by j4zzcat** [sudar/Arduino-Makefile#560]
I'm getting this during install.
```
Error: Calling <<-EOS.undent is disabled!                       
Use <<~EOS instead.             
/usr/local/Homebrew/Library/Taps/sudar/homebrew-arduino-mk/arduino-mk.rb:22:in `caveats'                                        
Please report this to the sudar/arduino-mk tap!                 
Or, even better, submit a PR to fix it!  
```

**Comment by tuna-f1sh** [comment]
This is a problem with the Homebrew formula, not Arudino-Makefile so you should make the issue there: https://github.com/sudar/homebrew-arduino-mk 

If you want a quick fix, it looks like you could try changing [line 22](https://github.com/sudar/homebrew-arduino-mk/blob/master/arduino-mk.rb#L16) to <<~EOS as it suggests.

**Comment by j4zzcat** [comment]
Done.
