### ISSUE TITLE
Consider migrating from github to gitlab

### ISSUE THREAD

**Issue by sej7278** [sudar/Arduino-Makefile#566]
Now M$ are acquiring github perhaps we need to think about alternatives?

https://gitlab.com/gitlab-com/gitlab-ultimate-for-open-source

https://wiki.debian.org/Salsa

**Comment by sudar** [comment]
@sej7278 

I see your point of view. It is very difficult for me also to trust Microsoft.

But I don't have 100% confidence on gitlab as well. Remember the episode where they lost content from production db without any backup?

Let's wait and see how Microsoft is treating github. Lot of people are claiming that it is a _new_ Microsoft.

At the first sign that things are going south, we can reconsider migrating away from github.
