### ISSUE TITLE
[Feature request]: #define MONITOR_BAUDRATE

### ISSUE THREAD

**Issue by James-E-A** [sudar/Arduino-Makefile#572]
Right now, the Makefile variable `MONITOR_BAUDRATE` is very useful. It's pre-defined, can be changed easily and globally, and allows the following extremely minimal and nearly elegant `Makefile` template/functional-skeleton:

````
ARDUINO_DIR	= /usr/share/arduino
#BOARD_TAG	= uno
#MCU		= atmega328p
CPPFLAGS	+= -DMONITOR_BAUDRATE=$(MONITOR_BAUDRATE)

include $(ARDUINO_DIR)/Arduino.mk

.phony minicom:
	minicom -b $(MONITOR_BAUDRATE) -D $(DEVICE_PATH)
````

This allows setting `MONITOR_BAUDRATE` on a per-compile, per-project, etc. basis. (Or, left "unset" i.e., ignored, it's defaulted to 9600 by the framework.)

However, shouldn't setting `CPPFLAGS` in the Makefile be unnecessary?

Since MONITOR_BAUDRATE is *already configured* as a part of the Arduino-Makefile framework, why isn't it also exported as a C-Definition, just like `LED_PIN`/etc are, for access in a program?

**Comment by tuna-f1sh** [comment]
[Yes](https://github.com/sudar/Arduino-Makefile/blob/master/Arduino.mk#L895)
