### ISSUE TITLE
Fedora 30: Gives ambiguous python shebang when building package

### ISSUE THREAD

**Issue by GreyGnome** [sudar/Arduino-Makefile#616]
When I am trying to build a package for Fedora 30, I get the following errors:

`*** ERROR: ambiguous python shebang in /usr/bin/ardmk-init: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
*** ERROR: ambiguous python shebang in /usr/bin/robotis-loader: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
*** ERROR: ambiguous python shebang in /usr/bin/ard-reset-arduino: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
`

To overcome this, I had to:

- tar xfz arduino-mk-1.6.0.tar.gz in the SOURCES directory

- cd arduino-mk-1.6.0/bin

- vim *

- replace all /usr/bin/env python with /usr/bin/env python2

- cd ../..

- tar cfz arduino-mk-1.6.0.tar.gz arduino-mk-1.6.0

- cd ../SPECS

Then I could do the rpmbuild -ba arduino-mk.spec

**Comment by sej7278** [comment]
Have a look at my python3 PR

**Comment by sej7278** [comment]
fixed in #e6881e2a43f02e0abf22bf28abc46b3c2e406d84
